name: GitHub Actions test
on: [push]
jobs:
  My-test-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is triggered by ${{ github.event_name }}"
      - run: echo "OS type = ${{ runner.os }}"
      - run: echo "repository = ${{ github.repository }}"
      - run: echo "git branch = ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Repository ${{ github.repository }} is cloned to the runner."
      - name: List files in the repository
        run: |
          ls -l ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
