name: GitHub Actions test
on: [push]
jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is triggered by ${{ github.event_name }}"
      - run: echo "OS type = ${{ runner.os }}"
      - run: echo "repository = ${{ github.repository }}"
      - run: echo "git branch = ${{ github.ref }}"
      - name: ls the workspace part 1
        run: pwd; ls -al ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Repository ${{ github.repository }} is cloned to the runner."
      - name: ls the workspace part 2
        run: ls -l ${{ github.workspace }}
      - name: OS info
        run: |
            uname -a
            hostname
      - run: echo "This job's status is ${{ job.status }}."
  my-job-2:
    runs-on: ubuntu-18.04
    steps:
      - name: step 1 (host info)
        run: |
          uname -a
          hostname
          cat /proc/cpuinfo |grep ^processor
          cat /proc/cpuinfo |grep ^'model name' | uniq
          curl https://ipinfo.io/ip
      - name: step 2 (uptime)
        run: |
          uptime
      - name: step 3 (status)
        run: echo "job status = ${{ job.status }}."
        
  
